#To Run this playbook without Ansible Tower via engine(in Check Mode): ansible-playbook -C rhel6to7.yml
#To Run this playbook without Ansible Tower via engine(in RUN Mode): ansible-playbook rhel6to7.yml
---
- name: Rhel upgrade 6.10 to 7.6
  hosts: all
  gather_facts: yes
  tasks:
  - name: RHEL Distribution Version
    debug: msg="RHEL version is {{ ansible_distribution_version}}"
  - name: Rhel version check
    debug: msg="Proceed with RHEL Upgrade validating RHEL version check"
    failed_when: ({{ ansible_distribution_version }} == 7.4 or {{ ansible_distribution_version }} == 7.5 or {{ ansible_distribution_version }} == 7.6)
  - name: Register to Red Hat subscription manager
    command: subscription-manager register --username rdodia --password ****
    ignore_errors: yes
  - name: List Available subsriptions
    command: subscription-manager list --available
  - name: Attach subscription manager to the pool ID
    command: subscription-manager attach --pool=8a85f98260c27fc50160c323263339ff
    ignore_errors: yes
  - name: Enable Repos for required RPMS needed for migration
    command: subscription-manager repos --enable rhel-6-server-extras-rpms 
  - name: Enable Repos for required RPMS needed for migration
    command: subscription-manager repos --enable rhel-6-server-optional-rpms
  - name: Install preupgrade-assistant package
    yum: name=preupgrade-assistant state=installed 
  - name: Install preupgrade-assistant-el6toel7 package
    yum: name=preupgrade-assistant-el6toel7 state=installed 
  - name: Install preupgrade-assistant-el6toel7-data
    yum: name=preupgrade-assistant-el6toel7-data state=installed 
  - name: Install preupgrade-assistant-ui
    yum: name=preupgrade-assistant-ui state=installed   
  - name: Install redhat-upgrade-tool
    yum: name=redhat-upgrade-tool state=installed
  - name: Running the Preupgrade Assistant as a Root user for migration 
    command: preupg
  - name: Enable SE Status
    command: semodule -r sandbox
  - name: OS Upgrade
    command: redhat-upgrade-tool --iso /opt/path-dvd.iso --cleanup-post
    notify: RestartServer
  - name: Validate RHEL version
    debug: msg="RHEL version is 7.6"
  - name: OS Upgrade Status
    debug: msg="OS Successfully migrated from RHEL 6.10 to 7.6"
  handlers:
  - name: RestartServer
    command: reboot
