---
- name: Rhel upgrade 6.10 to 7.6
  hosts: all
  tasks:
  - name: Check Rhel version
    command: cat /etc/redhat-release
  - name: Enable Repos
    command: subscription-manager repos --enable rhel-6-server-extras-rpms 
  - name: Enable Repos
    command: subscription-manager repos --enable rhel-6-server-optional-rpms
  - name: Install preupgrade-assistant package
    yum: name=preupgrade-assistant state=installed 
  - name: Install preupgrade-assistant-el6toel7 package
    yum: name=preupgrade-assistant-el6toel7 state=installed 
  - name: Install preupgrade-assistant-el6toel7-data
    yum: name=preupgrade-assistant-el6toel7-data state=installed 
  - name: Install preupgrade-assistant-ui
    yum: name=preupgrade-assistant-ui state=installed   
  - name: Install redhat-upgrade-tool
    yum: name=redhat-upgrade-tool state=installed
  - name: preupg
    command: preupg
  - name: OS Upgrade
    command: redhat-upgrade-tool --iso /opt/path-dvd.iso --cleanup-post
