---
- name: Rhel upgrade 6.10 to 7.6
  hosts: all
  gather_facts: yes
  tasks:
  - name: Distribution version
    debug: msg="Rhel version is {{ ansible_distribution_version}}"
  - name: Rhel version check
    debug: msg="Proceed with RHEL Upgrade validating RHEL version check"
    failed_when: "{{ ansible_distribution_version }} == 6.10"
